### PR TITLE
Fix marko-widgets #55. Callback can be left out.

### PR DESCRIPTION
**Pull request by austinkelleher**
Fixes https://github.com/raptorjs/marko-widgets/issues/55

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
Hi @austinkelleher, thanks for the quick fix on this issue! Unfortunately I wasn't able to review your PR until now, but your change looks good. Thank you for the contribution!

**Comment by patrick-steele-idem** [comment]
New version published: `raptor-renderer@1.4.3`

**Comment by austinkelleher** [comment]
:thumbsup:

**Comment by maberer** [comment]
Wow that was fast - thank you.
I tested it and it works great.

**Pull request merged**
